---
- name: Check whether autoupdate LaunchAgent is already installed
  stat:
    path: '{{ item }}'
  loop:
    - "{{ macprefs_launch_agent }}.plist"
  register: launch_agent_stat

- name: Check result
  debug:
    var: launch_agent_stat
  when: verbose | bool

- name: try to export MACPREFS_BACKUP_DIR
  command: export MACPREFS_BACKUP_DIR="{{ macprefs_backup_dir | expanduser }}"

- name: Install Macprefs LaunchAgent
  template:
    src: picture.dsimport.j2
    dest: "{{ item }}"
    mode: 0755
  vars:
    launch_agent_name: "{{ macprefs_launch_agent }}"
    regular_backup_interval_seconds: "{{ macprefs_regular_backup|int }}"
  when:
    - macprefs_backup.stat.isreg is defined
    - macprefs_backup.stat.isreg
  notify:
    - load LaunchAgent
    - restart launchd
...
