---
- name: Install Macprefs Cron job
  cron:
    name: Macprefs backup
    minute: "0/{{ macprefs_regular_backup|int }}"
    job: "{{ item }}"
  loop:
    - "MACPREFS_BACKUP_DIR='{{ macprefs_backup_dir }}' /usr/local/bin/macprefs -v backup > {{ macprefs_log  }} 2>&1"
