---
- name: Check whether autoupdate LaunchAgent is already installed
  stat:
    path: '{{ item }}'
  loop:
    - "{{ macprefs_launch_agent }}.plist"
  register: macprefs_launch_agent

- name: macprefs_launch_agent stats
  debug:
    var: macprefs_launch_agent
  when: verbose | bool

- name: try to export MACPREFS_BACKUP_DIR
  shell: export MACPREFS_BACKUP_DIR="{{ macprefs_backup_dir | expanduser }}"

- name: Install Macprefs LaunchAgent
  template:
    src: picture.dsimport.j2
    dest: "{{ item }}"
    mode: 0755
  vars:
    launch_agent_name: "{{ macprefs_launch_agent }}"
    regular_backup_interval_seconds: "{{ macprefs_regular_backup|int }}"
  when:
    - macprefs_launch_agent.stat.isreg is defined
    - macprefs_launch_agent.stat.isreg
  notify:
    - load LaunchAgent
    - restart launchd
...
