---
- name: Check whether autoupdate LaunchAgent is already installed
  stat:
    path: '{{ item }}'
  loop:
    - "{{ macprefs_launch_agent }}.plist"
  register: macprefs_launch_agent_file

- name: macprefs_launch_agent_file stats
  debug:
    var: macprefs_launch_agent_file.results[0]
  when: verbose | bool

- name: try to export MACPREFS_BACKUP_DIR
  shell: export MACPREFS_BACKUP_DIR="{{ macprefs_backup_dir | expanduser }}"

- name: Install Macprefs LaunchAgent
  template:
    src: com.github.clintmod.macprefs.plist.j2
    dest: "/Users/{{ target_user_id }}/Library/LaunchAgents/{{ macprefs_launch_agent }}.plist"
    mode: 0600
  vars:
    launch_agent_name: "{{ macprefs_launch_agent }}"
    regular_backup_interval_seconds: "{{ macprefs_regular_backup|int }}"
  when:
    - not macprefs_launch_agent_file.results[0].stat.exists|default(no)|bool
  notify:
    - load LaunchAgent
