- name: FATAL
  fail: msg="This role is only compatible with macOS"
  when: ansible_facts['os_family'] != 'Darwin'

- name: Setup macprefs
  block:
  - include_tasks: install-macprefs.yml

  - name: Fails if version is 1.0.26, and trigger 'rescue' that will verify if the patch is needed
    block:
    - name: Verify if Macpref version is 1.0.26
      lineinfile:
        dest: "{{ macprefs_bin_path }}/version.py"
        state: present
        regexp: '^.*1.0.26.*$'
      check_mode: yes
      register: macpref_version
      failed_when: macpref_version.changed

    rescue:
    - include_tasks: patch-with-marcomc-d79da5d.yml

  - name: User specific tasks
    block:
    - include_tasks: set-macprefs-backup-dir.yml
    - include_tasks: configure-launch-agent.yml
      when: macprefs_regular_backup|int > 0
    # - include_tasks: restore-macprefs-backup.yml
    become: "{{ target_user_id != ansible_user_id }}"
    become_user: "{{ target_user_id }}"
  # end block
  when: ansible_facts['os_family'] == 'Darwin'
