---
- name: Normalise Macprefs backup dir path
  set_fact:
    macprefs_backup_dir: "{{ item }}"
  loop:
    - "{{ macprefs_backup_dir | expanduser }}"

- name: Normalise Macprefs log dir path
  set_fact:
    macprefs_log: "{{ item }}"
  loop:
    - "{{ macprefs_log | expanduser }}"
