---
- name: Apply patch to macprefs 1.0.26 to support Python3
  patch:
    src: macprefs-1.0.26-marcomc-8bce8b8.patch
    basedir: '/usr/local/Cellar/macprefs/1.0.26/bin/'
    strip: 0
  register: patch_result

- name: patch_result
  debug:
    var: patch_result
  when: verbose|bool
