---
- name: Look for Macprefs backup dir '{{ macprefs_backup_dir | expanduser }}'.
  stat:
    path: "{{ macprefs_backup_dir | expanduser | mandatory }}"
  register: macprefs_backup

- name: Run Macprefs restore if MacPref Backup dir '{{ macprefs_backup_dir | expanduser }}' is present.
  shell: "{{ item }}"
  loop:
    - "$(command -v macprefs) -v restore > {{ macprefs_log | expanduser }} 2>&1"
  environment:
    MACPREFS_BACKUP_DIR: "{{ macprefs_backup_dir | expanduser }}"
  become: yes
  register: macprefs_restore
  ignore_errors: yes
  when:
  - macprefs_backup.stat.isdir is defined
  - macprefs_backup.stat.isdir
  changed_when: false
